### PR TITLE
Fixes guards that prevent repainting when there are no changes (issue #11)

### PR DESCRIPTION
**Pull request by dsummersl**
This PR also begins the process of cleaning up the python source files - it was one file about 1k lines long. This cuts the main python file size in half, by splitting out functions into their own python files.

### CODE REVIEW

**Comment by simnalamburt** [comment]
Acknowledged, thank you for your PR! Testing...

**Comment by simnalamburt** [comment]
I tested it with Vim 7.4 on OS X with `+python` option, and I'm using `Python 2.7.9`. It doesn't work on my machine in some reason, and I'm currently investigating this issue.

**Comment by dsummersl** [comment]
Ah...I think it might have been how I setup the python system path - I may have assumed a specific project name. Try this fix?

**Comment by simnalamburt** [comment]
Woo Thanks! Testing..

**Comment by simnalamburt** [comment]
Awesome! Much better startup time and no lag on trivial cases! :+1: It worked with the platforms below:

* Vim 7.4 with `+python`, Python 2.7.6, Ubuntu 14.04.2 LTS,
* Vim 7.4 with `+python`, Python 2.7.9, OS X Yosemite

And it caused problem with the platform below (it was used with #8):

* Vim 7.4 with `+python3`, Python 3.4.3, Arch Linux, `let g:gundo_prefer_python3 = 1`



Look's like python2 vs 3 problem again. Trying to fix....

**Comment by dsummersl** [comment]
I am so thankful you're doing this extra testing - thank you! I gotta get p3 installed on my system before I can test this. I'll take a look once I get that straight...

**Comment by dsummersl** [comment]
Try this out again? I made path fixes for python3.

**Comment by simnalamburt** [comment]
Sorry for the late reply, I've been busy for a while. I'll try this.

**Comment by simnalamburt** [comment]
@dsummersl It works perfect now. :+1: Thanks!

**Comment by pjambet** [comment]
I'm having the same issue on one of my machine (`No module named mundo.node`), both with vim and neovim

- vim `7.4` with `+python`, Python 2.7.10, OS X 10.11 El Capitan
- nvim `0.1.0-dev commit: a03af86cc28d9e755f5941b5dfaf54d003a1ad97` Python 2.7.10, OS X 10.11 El Capitan

It works well on my other machine, again both with vim & neovim, with Python 2.7.10 on OS X 10.10 Yosemite

The first machine, the non functioning one, used to be my main development computer for my Python projects so I guess there might some weird python setup, maybe with virtualenv?

Python is installed with `brew` on both machines.

Let me know if there is more information I could provide to help debug this. In the meantime, I locked the version to the commit before this PR was merged on the non functioning computer, this works well for now.

PS: Thanks again for your work on this plugin, it's awesome!

**Comment by dsummersl** [comment]
Hi @pjambet, so you see `'GundoRenderGraph' is not defined`?  Try executing the following:

    :echo has('python') . has('python3')

(Will probably be 10, but as long as there is at least one 1, you should be good...)

What is the directory where you installed mundo (eg, `~/.vim/bundle/vim-mundo`)?

**Comment by pjambet** [comment]
Hey @dsummersl 

Yes, I see 'GundoRenderGraph' is not defined, among other errors, here is the exact issue I get when trying to run `:GundoToggle`

```
Error detected while processing function gundo#GundoToggle[1]..<SNR>70_GundoToggle[6]..<SNR>70_GundoOpen:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pierre/.homesick/repos/dotfiles/home/.vim/bundle/vim-mundo/autoload/gundo.py", line 30, in <module>
    from mundo.node import Nodes
ImportError: No module named mundo.node
line    7:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
"__Gundo_Preview__" [New File]
Error detected while processing function gundo#GundoToggle[1]..<SNR>70_GundoToggle[6]..<SNR>70_GundoOpen[30]..<SNR>70_GundoPython:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'GundoRenderGraph' is not defined
Error detected while processing function gundo#GundoToggle[1]..<SNR>70_GundoToggle[6]..<SNR>70_GundoOpen[31]..<SNR>70_GundoPython:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'GundoRenderPreview' is not defined
```

`:echo has('python') . has('python3')` returns `10` on both machines

Mundo is installed in a directory (`~/.homesick/repos/dotfiles/home/.vim/bundle/vim-mundo`), and `~/.homesick/repos/dotfiles/home/.vim` is symlinked in `~`. Same setup on both machine.

**Pull request merged**
