### PR TITLE
[RFC]Rename gundo.vim to mundo.vim

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by wsdjeg** [comment]
@simnalamburt I hava finished this PR,can you review it?

**Comment by wsdjeg** [comment]
Should we keep these codes
```vim
command! -nargs=0 GundoToggle call gundo#GundoToggle()
command! -nargs=0 GundoShow call gundo#GundoShow()
command! -nargs=0 GundoHide call gundo#GundoHide()
command! -nargs=0 GundoRenderGraph call gundo#GundoRenderGraph()
```

**Comment by simnalamburt** [comment]
I reviewed overall commits, let me test it in my environment too.

About those `GundoToogle` and etc, I think we might be better if we preserve backward compatibility. Someone must use those commands to use it with keybinding. And also I want to add @dsummersl as one of the maintainer in https://github.com/wsdjeg/vim-mundo/commit/129116b8472173793484c07cc870a07ad2e8da95#diff-56e95d624f15e34bbd03a07ac0981f1eR4 but let's do that after I create the `vim-mundo` group.

Thank you for your commitment!

@dsummersl How does it look for you?

**Comment by wsdjeg** [comment]
So I think maybe we should not remove this commands now.

**Comment by simnalamburt** [comment]
That's right :+1:

**Comment by wsdjeg** [comment]
now you can use :h mundo etc. to open help doc

**Comment by dsummersl** [comment]
Hey @wsdjeg & @simnalamburt checking it out this AM, sorry for the delay. Thanks for working on this!

I'm not sure about whether to move the commands right off. My intuition tells me that this is a breaking change (regardless of the `GundoToggle` change). If thats the case we probably ought to make the name change in the interest of minimizing the # of breaking change releases.

Are we using semantic versioning? I....think we are? If so we should make this change a major version release.

Get back to you all later today.

**Comment by wsdjeg** [comment]
sorry for my pool english,I wounder if I misunderstand,I think there is no need to use Gundo any more,the plugin is Mundo,and we must change it . better than change it in the feture.meybe we can add two files for the old user.
1. /plugin/gundo.vim
```vim
+command! -nargs=0 GundoToggle call mundo#MundoToggle()
+command! -nargs=0 GundoShow call mundo#MundoShow()
+command! -nargs=0 GundoHide call mundo#MundoHide()
+command! -nargs=0 GundoRenderGraph call mundo#MundoRenderGraph()
```
2. /autoload/gundo.vim
```vim
" for the old config g:var
```

## but in the near feture, we should delete them.

**Comment by wsdjeg** [comment]
any update for this PR?

**Comment by dsummersl** [comment]
I like @wsdjeg's suggestion that we make this the new 'major release', and break the Gundo function. But, I think we should give old users some warnings, so they know how to fix their configurations.

We already do this for both `gundo_*` and `mundo_*` style configurations, so we're good there...I think we should:

 * Add an `echoerr` to `mundo#util#set_default()` function. When a `gundo_*` variable is detected report something like "{{variable}} is deprecated! Please change your setting to {{new name}}".
 * Rename the Gundo* commands to Mundo* commands.
 * Add new Gundo* commands that call a new function that reports `echoerr "Gundo* commands are deprecated. Please change to their corresponding Mundo* command"`.
 * We do use semantic versioning(!), lets make this the official release of a hard change: Modify the `MundoChangelog` section: change `v3.X - WIP` to `v3.0.0`.

I'd be happy to help if you'd rather I do that...tested out your branch locally and it works for me thus far.

**Comment by wsdjeg** [comment]
ok let me try to update the code now

**Comment by dsummersl** [comment]
awesome, thank you!

**Comment by wsdjeg** [comment]
I hava finished this PR,can you review it? thanks a lot!

**Comment by dsummersl** [comment]
Works great for me.

@simnalamburt, does this look okay to you as well?

**Comment by wsdjeg** [comment]
#### Test with old g:var and old command!

**Comment by dsummersl** [comment]
had a chance to check this out @simnalamburt ?

**Comment by simnalamburt** [comment]
@dsummersl Sorry, I don't have time to test this on my own for right now. Let me entrust this PR to you.

**Comment by wsdjeg** [comment]
now it is the time for new year , let us just enjoy it

**Comment by simnalamburt** [comment]
###### Note for @dsummersl 
I'm Korean and wsdjeg is Chinese, and we are usually very busy in early Feburary because Asian New Year's Day uses [lunar calendar](https://en.wikipedia.org/wiki/Lunar_calendar).

**Comment by dsummersl** [comment]
Happy New Year guys!

Over here in the Eastern USA we had our New Years a month ago...

**Pull request merged**
